# Generated by Django 4.1.7 on 2023-03-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_submission_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='annual_revenue',
            field=models.IntegerField(null=True),
        ),
    ]
